# Config file for automatic testing at travis-ci.org

language: python
python: "3.5"
sudo: false

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=flake8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install tox
  - pip install coveralls

services:
  - redis-server

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success: coveralls
